import React, { useState } from 'react';
import { useForm } from 'react-hook-form';
// import useAuth from '../../../hooks/useAuth';
import { Link, useLocation, useNavigate } from 'react-router';
import SocialLogin from '../SocialLogin/SocialLogin';
import useAuth from '../../../hooks/useAuth';

const Login = () => {
    const { register, handleSubmit, formState: { errors } } = useForm();
    const { signInUser } = useAuth();
    const location = useLocation();
    const navigate = useNavigate();
    const [loginError, setLoginError] = useState('');
    const [isLoading, setIsLoading] = useState(false);


    const handleLogin = async (data) => {
        setLoginError('');
        setIsLoading(true);
        
        try {
            console.log('form data', data);
            const result = await signInUser(data.email, data.password);
            console.log('Login successful:', result.user);
            
            // Navigate to home page after successful login
            // JWT token is automatically generated by AuthProvider
            navigate(location.state?.from?.pathname || '/', { replace: true })
        } catch (error) {
            console.log('Login error:', error);
            setLoginError(error.message || 'Failed to login. Please try again.');
        } finally {
            setIsLoading(false);
        }
    }

    return (
        <div className="card bg-base-100 w-full mx-auto max-w-sm shrink-0 shadow-2xl">
            <h3 className="text-3xl text-center">Welcome back</h3>
            <p className='text-center'>Please Login</p>
            <form className="card-body" onSubmit={handleSubmit(handleLogin)}>
                <fieldset className="fieldset">
                    {/* email field */}
                    <label className="label">Email</label>
                    <input type="email" {...register('email', { required: true })} className="input" placeholder="Email" />
                    {
                        errors.email?.type === 'required' && <p className='text-red-500'>Email is required</p>
                    }

                    {/* password field */}
                    <label className="label">Password</label>
                    <input type="password" {...register('password', { required: true, minLength: 6 })} className="input" placeholder="Password" />
                    {
                        errors.password?.type === 'minLength' && <p className='text-red-500'>Password must be 6 characters or longer </p>
                    }

                    {/* Error message */}
                    {loginError && <p className='text-red-500 mt-2'>{loginError}</p>}

                    <div><a className="link link-hover">Forgot password?</a></div>
                    <button 
                        type="submit"
                        disabled={isLoading}
                        className="btn btn-neutral mt-4"
                    >
                        {isLoading ? 'Logging in...' : 'Login'}
                    </button>
                </fieldset>
                <p>New to Zap Shift <Link
                    state={location.state}
                    className='text-blue-400 underline'
                    to="/register">Register</Link></p>
            </form>
            <SocialLogin></SocialLogin>
        </div>
    );
};

export default Login;