import React, { useState } from 'react';
import { useForm } from 'react-hook-form';
import useAuth from '../../../hooks/useAuth';
import { Link, useLocation, useNavigate } from 'react-router';
import SocialLogin from '../SocialLogin/SocialLogin';
import axios from 'axios';
import useAxiosSecure from '../../../hooks/useAxiosSecure';

const Register = () => {
    const { register, handleSubmit, formState: { errors } } = useForm();
    const { registerUser, updateUserProfile } = useAuth();
    const location = useLocation();
    const navigate = useNavigate();
    const axiosSecure = useAxiosSecure();
    const [registrationError, setRegistrationError] = useState('');
    const [isLoading, setIsLoading] = useState(false);


    const handleRegistration = async (data) => {
        setRegistrationError('');
        setIsLoading(true);

        try {
            const profileImg = data.photo[0];

            // 1. Create user in Firebase
            const authResult = await registerUser(data.email, data.password);
            console.log('User created in Firebase');

            // 2. Store the image in form data
            const formData = new FormData();
            formData.append('image', profileImg);

            // 3. Send the photo to ImgBB and get the URL
            const image_API_URL = `https://api.imgbb.com/1/upload?key=${import.meta.env.VITE_image_host_key}`;

            const imageRes = await axios.post(image_API_URL, formData);
            const photoURL = imageRes.data.data.url;
            console.log('Image uploaded successfully');

            // 4. Create user in the database
            const userInfo = {
                email: data.email,
                displayName: data.name,
                photoURL: photoURL,
                uid: authResult.user.uid
            };

            try {
                const dbRes = await axiosSecure.post('/users', userInfo);
                if (dbRes.data.insertedId) {
                    console.log('User created in the database');
                }
            } catch (dbError) {
                console.error('Error creating user in database:', dbError);
                // Don't fail if database creation fails - user is already created in Firebase
            }

            // 5. Update user profile in Firebase
            const userProfile = {
                displayName: data.name,
                photoURL: photoURL
            };

            await updateUserProfile(userProfile);
            console.log('User profile updated in Firebase');

            // JWT token is automatically generated by AuthProvider when user state changes
            // Navigate to home page after successful registration
            navigate(location.state?.from?.pathname || '/', { replace: true });
        } catch (error) {
            console.error('Registration error:', error);
            setRegistrationError(error.message || 'Failed to register. Please try again.');
        } finally {
            setIsLoading(false);
        }
    }

    return (
        <div className="card bg-base-100 w-full mx-auto max-w-sm shrink-0 shadow-2xl">
            <h3 className="text-3xl text-center">Welcome to Zap Shift</h3>
            <p className='text-center'>Please Register</p>
            <form className="card-body" onSubmit={handleSubmit(handleRegistration)}>
                <fieldset className="fieldset">
                    {/* name field */}
                    <label className="label">Name</label>
                    <input type="text"
                        {...register('name', { required: true })}
                        className="input"
                        placeholder="Your Name" />
                    {errors.name?.type === 'required' && <p className='text-red-500'>Name is required.</p>}

                    {/* photo image field */}
                    <label className="label">Photo</label>

                    <input type="file" {...register('photo', { required: true })} className="file-input" placeholder="Your Photo" />

                    {errors.photo?.type === 'required' && <p className='text-red-500'>Photo is required.</p>}

                    {/* email field */}
                    <label className="label">Email</label>
                    <input type="email" {...register('email', { required: true })} className="input" placeholder="Email" />
                    {errors.email?.type === 'required' && <p className='text-red-500'>Email is required.</p>}

                    {/* password */}
                    <label className="label">Password</label>
                    <input type="password" {...register('password', {
                        required: true,
                        minLength: 6,
                        // pattern: /^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[^A-Za-z0-9]).+$/
                    })} className="input" placeholder="Password" />
                    {
                        errors.password?.type === 'required' && <p className='text-red-500'>Password is required.</p>
                    }
                    {
                        errors.password?.type === 'minLength' && <p className='text-red-500'>
                            Password must be 6 characters or longer
                        </p>
                    }
                    {
                        errors.password?.type === 'pattern' && <p className='text-red-500'>Password must have at least one uppercase, at least one lowercase, at least one number, and at least one special characters</p>
                    }

                    {/* Error message */}
                    {registrationError && <p className='text-red-500 mt-2'>{registrationError}</p>}

                    <div><a className="link link-hover">Forgot password?</a></div>
                    <button 
                        type="submit"
                        disabled={isLoading}
                        className="btn btn-neutral mt-4"
                    >
                        {isLoading ? 'Registering...' : 'Register'}
                    </button>
                </fieldset>
                <p>Already have an account <Link
                    state={location.state}
                    className='text-blue-400 underline'
                    to="/login">Login</Link></p>
            </form>
            <SocialLogin></SocialLogin>
        </div>
    );
};

export default Register;